### ISSUE TITLE
Bread recipe - how does this look?

### ISSUE THREAD

**Issue by oharac** [eds211-projtest/bread#1]
Here's a recipe I found on line - what do people think?  Is anyone gluten free?

https://www.bowlofdelicious.com/dutch-oven-bread/

**Comment by samanthacsik** [comment]
Looks good, but how do we think about starting with [The Easiest Loaf of Bread You'll Ever Bake](https://www.kingarthurbaking.com/recipes/the-easiest-loaf-of-bread-youll-ever-bake-recipe) first?

**Comment by oharac** [comment]
OK, we're done with this one, yaya
